### ISSUE TITLE
Mention Google's Advanced Protection Program (GAPP)

### ISSUE THREAD

**Issue by ghost** [iAnonymous3000/google-hardening-guide#1]
Hello there! 

It would be great to mention in this guide the existence of GAPP, or the Google Advanced Protection Program.

This program is designed for people like journalists, politicians or other types of people with high threat models who need much higher security. It will have : 

- Stricter TOTP with only physical security keys like YubiKeys or Google Titan.
- Only Google and verified third-party apps can access account data
- Scan incoming emails on Gmail accounts for phishing attempts
- Strict safe browser scanning with Google Chrome
- Strict recovery process for accounts with lost credentials

Also, it will : 

- Not allow app installation outside the Google Play Store, the OS vendor's app store, or via adb
- Have mandatory automatic device scanning with Play Protect
- Warn you about unverified applications

Info comes from : https://www.privacyguides.org/en/os/android-overview/#advanced-protection-program

**Comment by iAnonymous3000** [comment]
Thank you for your suggestion. I've updated the guide to incorporate a section on GAPP, emphasizing its critical security features and its relevance to high-risk individuals.

I hope this addition meets your expectations. Please let me know if there's anything else we can improve or add. Your feedback is invaluable.
